[package]
name = "elephentity-codegen-wpgraphql"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Elephentity wpgraphql manifest builder"

[[bin]]
name = "eleph-gen-wpgraphql"
path = "rust/main.rs"

[dependencies]
serde_json = { version = "1", features = ["preserve_order"] }
serde = { version = "1", features = ["derive"] }
indexmap = { version = "2", features = ["serde"] }
